(require 'eglot)
(require 'go-mode)
(require 'nix-mode)
(require 'terraform-mode)
(require 'haskell-mode)
(require 'python-mode)
(require 'markdown-mode)
(require 'yaml-mode)
(require 'elm-mode)
(require 'zig-mode)
(require 'lua-mode)
(require 'rust-mode)
(require 'tuareg)
(require 'd-mode)

(setq py-keep-windows-configuration t)
(setq py-split-window-on-execute nil)
(setq py-shell-switch-buffers-on-execute-p nil)

(add-hook 'go-mode-hook #'eglot-ensure)
(add-hook 'nix-mode-hook #'eglot-ensure)
(add-hook 'terraform-mode-hook #'eglot-ensure)
(add-hook 'c-mode-hook #'eglot-ensure)
(add-hook 'c++-mode-hook #'eglot-ensure)
(add-hook 'haskell-mode-hook #'eglot-ensure)
(add-hook 'python-mode-hook #'eglot-ensure)
(add-hook 'markdown-mode-hook #'eglot-ensure)
(add-hook 'yaml-mode-hook #'eglot-ensure)
(add-hook 'elm-mode-hook #'eglot-ensure)
(add-hook 'zig-mode-hook #'eglot-ensure)
(add-hook 'lua-mode-hook #'eglot-ensure)
(add-hook 'rust-mode-hook #'eglot-ensure)
(add-hook 'tuareg-mode-hook #'eglot-ensure)
(add-hook 'd-mode-hook #'eglot-ensure)

(with-eval-after-load 'eglot
  (add-to-list 'eglot-server-programs
	       '(d-mode . ("serve-d"))))
