#+author: Ilya Savitsky

* Hi there! My name is Ilya 👋
** Who am I?
I'm a software engineer based in Manchester UK. You can find my resume [[https://github.com/ipsavitsky/resume/releases/download/v5.1/resume.en_US.pdf][here]].
** What is in this repo?
This repo contains this ~org~ file as well as a lately added ~terraform~ files that contains as much configuration as it is possible without a recreation of all resources. All new repos I will create there.
** What is on this account
There is also [[https://github.com/ipsavitsky/greedy-scheduling]] which is a comprehensive greedy scheduling algorithm, described in a paper I co-authored.
Every repository starting with ~cmc-~ is a repo for a course in my uni.
Some of my personal projects:
1. [[https://github.com/ipsavitsky/wiki_search][Wiki search tool]] :: A tool in python that searches Wiki of any kind and prints it prettily in your console, like a ~man~ page.
2. [[https://github.com/ipsavitsky/tts-alice-bot][Alice TTS bot]] :: A Telegram bot that generates an audio message from a long text message using Yandex SpeechKit.
Some of my university projects (most of those have descriptions in Russian):
1. [[https://github.com/ipsavitsky/simple_shell][Simple shell]] :: A shell written in C that supports parallel launches, pipes and redirects (the whole =&=, =|= things).
2. [[https://github.com/ipsavitsky/sql_interpreter][SQL interpreter]] :: An SQLite-style local-first SQL interpreter with a custom DBMS.
3. [[https://github.com/ipsavitsky/graphs][Graph library]] :: A graph library that uses COO to store graphs.
4. [[https://github.com/ipsavitsky/mvs-asvk][A random search scheduling algorithm]] :: A parallelized random search processor scheduling algorithm.
I also keep solutions to coding challanges here:
1. [[https://github.com/ipsavitsky/leetcode-solutions][Leetcode]]
2. [[https://github.com/ipsavitsky/codewars-solutions][Codewars]]
Whenever I learn a new language with new concepts my favourite excercise is writing Conway's game of life which I keep here: [[https://github.com/orgs/games-of-life/repositories]]
