name: Lint
on:
  push:
    branches:
      - "*"
jobs:
  nix:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Install nix
        uses: DeterminateSystems/nix-installer-action@92148bb48b9a0c5458c53dd0b368fbfbfbaa3210
      - name: Nix flake check
        run: nix flake check
