name: Lint
on:
  push:
    branches:
      - "*"
jobs:
  nix:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Install nix
        uses: DeterminateSystems/nix-installer-action@4a754ab0c192f4d12cf88b5954b9dd13fd2d612e
      - name: Nix flake check
        run: nix flake check
