name: Lint
on:
  push:
    branches:
      - "*"
jobs:
  nix:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Install nix
        uses: DeterminateSystems/nix-installer-action@9a59e15a74545c99a626ba594edcd0d02189e670
      - name: Nix flake check
        run: nix flake check
