name: Lint nix flake

on:
  push:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check Nix flake inputs
        uses: DeterminateSystems/flake-checker-action@v4
        with:
          fail-mode: true
          send-statistics: false
          flake-lock-path: ./flake.nix

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v3

      - name: Build default package
        run: nix build
